# Generated by Django 5.2.1 on 2025-07-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_topic_alter_post_content_alter_post_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(blank=True, to='blog.topic'),
        ),
    ]
