# Generated by Django 5.2.1 on 2025-07-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(help_text='A URL-friendly version of the topic name', unique=True),
        ),
    ]
